#### DEFAULT ####
# ambientes definidos em: development,testing,staging e production
## configurações de controle da url
default:
 development:
  address_uri: 192.168.33.101/dwphp-2.0/
  use_https: Off
  use_www: Off

 testing:
  address_uri: /
  use_https: Off
  use_www: Off

 staging:
  address_uri: dwphp.dezwork.com.br/
  use_https: Off
  use_www: Off

 production:
  address_uri: /
  use_https: Off
  use_www: Off

 # configurações do banco de dados
 db_development:
  drive: pdo_mysql
  host: localhost
  username: root
  password: 123456
  database: dwphp
  encoding: utf8

 db_testing:
  drive:
  host:
  username:
  password:
  database:
  encoding:

 db_staging:
  drive: pdo_mysql
  host: mysql.dezwork.com.br
  username: ******
  password: ******
  database: ******
  encoding: utf8

 db_production:
  drive:
  host:
  username:
  password:
  database:
  encoding: