default:
     development:
          address_uri: /
          use_https: Off
          use_www: Off
     testing:
          address_uri: /
          use_https: Off
          use_www: Off
     staging:
          address_uri: /
          use_https: Off
          use_www: Off
     production:
          address_uri: /
          use_https: Off
          use_www: Off
     db_development:
          drive: pdo_mysql
          host: null
          username: null
          password: null
          database: null
          encoding: null
     db_testing:
          drive: pdo_mysql
          host: null
          username: null
          password: null
          database: null
          encoding: null
     db_staging:
          drive: pdo_mysql
          host: null
          username: null
          password: null
          database: null
          encoding: null
     db_production:
          drive: pdo_mysql
          host: null
          username: null
          password: null
          database: null
          encoding: null
